### ISSUE TITLE
Background pictures not loading

### ISSUE THREAD

**Issue by FalenDemon** [r-renato/hass-xiaomi-mi-flora-and-flower-care#3]
Hello!

Looks like there are some problems, but I have no idea where. I configured all stuff, Flower Care server - RU. That how it looks now in lovelace:
![Снимок2](https://user-images.githubusercontent.com/61520493/75442874-60e4b800-5971-11ea-9bea-a4327046ccf1.JPG)

Actually I tried to change card background via lovelace-card-mod, but it just dont load any pictures. (Tried on other cards, and it work)

Code:
`        - type: custom:xiaomi-mi-flora-and-flower-care-card
          name: "Юкка"
          style: |
            ha-card {
              background: rgba(50,50,50,0.3);
              background-image: url("/local/img/yukka.png");
              background-repeat: no-repeat;
              border-radius: 15px;
            }
          entity: plant.plant_yucca_elephantipes`
![Снимок3](https://user-images.githubusercontent.com/61520493/75443210-f8e2a180-5971-11ea-9b22-289bee2a5d1d.JPG)

**Comment by r-renato** [comment]
Hi,
did you check if the custom component working fine? Can you post here the custom component configuration? 

In any case, if you put it in debug mode you can see the retrieved data.
Thanks, Renato

**Comment by FalenDemon** [comment]
Thanks for fast reply! I'm pretty new to HA, what exactly I should send you?

Well, your card received suggested values for curtent plant like moisture and etc, so it works?

**Comment by r-renato** [comment]
1) post your custom component configuration, for example:
```
huahuacaocao:
  username: !secret huahuacaocao_user
  password: !secret huahuacaocao_password
  region: EU
```
2) in the configuration.yaml, put in debug mode the component:
```
# Logging
logger:
    custom_components.huahuacaocao: debug
```
so, check the ha log for any information about the huahuacaocao.

**Comment by FalenDemon** [comment]
Tried to use logger, got an error:
`Invalid config for [logger]: [custom_components.huahuacaocao] is an invalid option for [logger]. Check: logger->logger->custom_components.huahuacaocao. (See /config/configuration.yaml, line 8).`

huahuacaocao:
  username: b******ov@gmail.com
  password: ***
  region: RU

  - platform: huahuacaocao
    plant_id: "Yucca elephantipes"
    name: "Plant Yucca elephantipes"
    sensors:
      moisture: sensor.yukka_moisture
      battery: sensor.yukka_battery
      temperature: sensor.yukka_temperature
      conductivity: sensor.yukka_conductivity
      brightness: sensor.yukka_light_intensity
![Снимок4](https://user-images.githubusercontent.com/61520493/75448488-5e3b9000-597c-11ea-997b-170ac1986b97.JPG)

**Comment by r-renato** [comment]
Check your configuration.yaml, in general I put the logger definition at the bottom (check the indentation). This step is crucial know if ha reports errors.

Also, i suggest you to use UE as region, not RU.

My settings are:

```
huahuacaocao:
  username: !secret huahuacaocao_user
  password: !secret huahuacaocao_password
  region: EU

sensor:
  - platform: huahuacaocao
    plant_id: "zamioculcas zamiifolia"
    name: "Plant Zamioculcas Zamiifolia"
    sensors:
      moisture: sensor.xiaomi_flora_1_moisture
      battery: sensor.xiaomi_flora_1_battery
      temperature: sensor.xiaomi_flora_1_temperature
      conductivity: sensor.xiaomi_flora_1_conductivity
      brightness: sensor.xiaomi_flora_1_light_intensity
```
